[package]
name = "vim_mode_setting"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/vim_mode_setting.rs"

[dependencies]
gpui = { workspace = true }
serde = { workspace = true }
